apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "shipyard-delivery-simplenode"
  description: "3 stages delivery with an option for a hotfix deployment into staging and production"
spec:
  stages:
  - name: dev
    description: "Represents Dev Stage where all new artifacts will be deployed first."
    sequences:
    - name: delivery
      tasks:
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: functional
      - name: evaluation
      - name: release
      - name: approval
        properties:
          pass: automatic
          warning: automatic
  - name: staging
    description: "Represents Staging where good artifacts from dev will be promoted to. One exception is the hotfix sequence which allows direct deploy to staging!"
    sequences:
    - name: delivery
      triggeredOn:
      - event: dev.delivery.finished
      tasks:
      - name: monaco
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: release
    - name: rollback
      triggeredOn:
        - event: "staging.delivery.finished"
          selector:
            match:
              result: "fail"
      tasks:
        - name: rollback
    - name: delivery-hotfix
      tasks:
      - name: monaco
      - name: deployment
        properties:
          deploymentstrategy: direct
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: release
      - name: approval
        properties:
          pass: automatic
          warning: manual
  - name: production
    description: "Represents Production. All staging artifacts need manual approval except hotfixes. Hotfixes are auto-approved if passed!"
    sequences:
    - name: delivery
      triggeredOn:
      - event: staging.delivery.finished
      tasks:
      - name: monaco
      - name: deployment
        properties:
          deploymentstrategy: blue_green_service
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: release
    - name: rollback
      triggeredOn:
        - event: "production.delivery.finished"
          selector:
            match:
              result: "fail"
      tasks:
        - name: rollback
    - name: delivery-hotfix
      triggeredOn:
      - event: staging.delivery-hotfix.finished
      tasks:
      - name: monaco
      - name: deployment
        properties:
          deploymentstrategy: blue_green_service
      - name: test
        properties:
          teststrategy: performance
      - name: evaluation
      - name: release