apiVersion: v1
kind: Service
metadata:
  name: helloservice
  namespace: prometheus-qg-quality-gate
spec:
  selector:
    app: helloservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  type: ClusterIP
